ENV["FASTLANE_PASSWORD"] = "1HateInstagram1HateInstagram"
ENV["MATCH_KEYCHAIN_PASSWORD"] = "123456"
ENV["APP_IDENTIFIER"] = "com.taglife.taglife2"
ENV["TEAM_ID"] = "H26DA27U2W"
ENV["TEAM_NAME"] = "Alex Petrov"
ENV["FASTLANE_USER"] = "taglife@yandex.ru"

update_fastlane

default_platform(:ios)

platform :ios do

  desc "Description of what the lane does"
  lane :inc do
    get_build_number
    increment_build_number(xcodeproj: "Qooore.xcodeproj")
    increment_version_number()
  end

  desc "Get certificates"
  lane :get_certificates_or_generate do

    create_keychain(
      name: "KeychainName",
      password: "123456",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true
    )

    get_certificates

    get_provisioning_profile(
      app_identifier: ENV["APP_IDENTIFIER"],
      username: ENV["FASTLANE_USER"],
      team_id: ENV["TEAM_ID"],
      team_name: ENV["TEAM_NAME"],
    )

    gym(
      scheme: "Qooore",
      workspace: "Qooore.xcworkspace",
      clean: true,
      output_directory: './builds',
      output_name: "alpha_qooore",
      silent: false,
      xcargs: "-UseModernBuildSystem=NO",
      include_bitcode: true,
      export_method: "app-store",
      include_symbols: true,
    );

    sh('sh ../.github/scripts/clean_all.sh')
  end
end
