name: "IOS upload alpha"

on:
  push:
    branch: master

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Set up Ruby 2.6"
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: "Install gem Dependencies"
        run: gem install bundler && bundle install

      - name: "Xcode install"
        run: sudo xcode-select -switch /Applications/Xcode_11.5.app

      - name: "Pod install"
        run: "pod install"

      - name: "Fastlane recheck"
        run: "fastlane -v"

      - name: "Fastlane inc number"
        run: "bundle exec fastlane inc"

      - name: "Grant permissions"
        run: chmod +rx ./.github/scripts/tests_app.sh ./.github/scripts/clean_all.sh
      
      - name: "Nuke"
        run: bundle exec fastlane nuke distrubution

      - name: "Run get certificates"
        run: bundle exec fastlane get_certificates_or_generate

      - name: "delete"
        run: "sh ./.github/scripts/clean_all.sh"

      - name: "get commit"
        id: commit
        run: |
          str="$(jq '.head_commit.message' $GITHUB_EVENT_PATH)"
          echo ::set-output name=title::${str%%\\n*} | tr -d '"'
          echo ::set-output name=body::${str##*\\n} | tr -d '"'