name: "IOS upload alpha"

on:
  push:
    branches:
      - "release-*"

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Set up Ruby 2.6"
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: "Install gem Dependencies"
        run: gem install bundler && bundle install

      - name: "Xcode install"
        run: sudo xcode-select -switch /Applications/Xcode_11.5.app

      - name: "Pod install"
        run: "pod install"

      - name: "Fastlane recheck"
        run: "fastlane -v"

      - name: "Run tests"
        run: "sh ./.github/scripts/tests_app.sh"

      - name: "Fastlane inc number"
        run: "bundle exec fastlane inc_release"

      - name: "Grant permissions"
        run: sh ./.github/scripts/grant_permissions.sh

      - name: "Run get certificates"
        run: bundle exec fastlane get_certificates_or_generate
      
      # - name: "Build app"
      #   run: bundle exec fastlane buildling_app_release

      # - name: "Deploy app"
      #   run: sh ./.github/scripts/archive_build.sh

      # - name: "Export app"
      #   run: sh ./.github/scripts/export_app.sh

      - name: "Deploy TestFlight"
        run: bundle exec fastlane deploy_release

      # - name: "delete"
      #   run: "sh ./.github/scripts/clean_all.sh"